services:
  - type: web
    name: travelpath
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"
      - key: JWT_ACCESS_TOKEN_EXPIRES
        value: "86400"
      - key: API_COLOMBIA_BASE_URL
        value: https://api-colombia.com/api/v1
      - key: JWT_SECRET_KEY
        generateValue: true   # Render genera una clave segura automáticamente
      - key: DATABASE_URL
        sync: false           # Lo ingresas manualmente en el dashboard de Render
