services:

  - type: web
    name: travelpath-airport
    runtime: docker
    dockerfilePath: ./airport-service/Dockerfile
    dockerContext: ./airport-service
    envVars:
      - key: FLASK_DEBUG
        value: "false"

  - type: web
    name: travelpath
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_DEBUG
        value: "false"
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
      - key: AIRPORT_SERVICE_URL
        value: https://travelpath-airport.onrender.com
